//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace state_district_ddl
{
    using System;
    using System.Collections.Generic;
    
    public partial class DDL_Tab
    {
        public int Uid { get; set; }
        public int StateId { get; set; }
        public int DisId { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
    }
}
